#!/bin/bash
echo "Installing config"
echo "tmux"
cp -v ./tmux/tmux.conf ~/.tmux.conf
echo "zsh"
cp -v ./zsh/zshrc ~/.zshrc
cp -v ./zsh/*.theme ~/.oh-my-zsh/themes
echo "bash"
cp -v ./bash/bashrc ~/.bashrc
ehco "Fonts"
cp -v ./fonts/* ./.fonts
echo "Scripts"
mkdir ~/custom/scripts
cp ./scripts/* ~/custom/scripts
echo "vim"
cp -avr ./vim ~/.vim
echo "Config install complete."
echo "Open vim and execute :PluginInstall to install plugins."
