#!/bin/bash
echo "Updating config"
echo "tmux"
cp -avr ~/.tmux.conf ./tmux/tmux.conf 
echo "zsh"
cp -avr ~/.zshrc ./zsh/zshrc 
echo "bash"
cp -avr ~/.bashrc ./bash/bashrc 
echo "bin"
cp -avr ~/bin ./bin
echo "Custom"
cp -avr ~/custom/ ./custom
echo "vim"
cp -avr ~/.vim/* ./vim
rm -rf ./vim/bundle/YouCompleteMe
echo "Complete"
