" Specify a directory for plugins
" - For Neovim: stdpath('data') . '/plugged'
" - Avoid using standard Vim directory names like 'plugin'
call plug#begin('~/vimfiles/plugged')

" Make sure you use single quotes

" Shorthand notation; fetches https://github.com/junegunn/vim-easy-align
Plug 'tpope/vim-sensible'
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-surround'
Plug 'altercation/vim-colors-solarized'

" Multiple Plug commands can be written in a single line using | separators
" Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'

" On-demand loading
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }

" Initialize plugin system
call plug#end()

" Enable line numbering
set nu

" Remove clutter from the GUI
set guioptions=aem

" Font (required for lightline)
if has('gui_running')
    set guifont=Source\ Code\ Pro\ for\ Powerline\ Medium\ 10
endif
" Map Esc to something reachable
ino jk <esc>
cno jk <c-c>
vno v <esc>

" Some default settings
set clipboard=unnamed

" EasyAlign settings
" Start interactive EasyAlign in visual mode (e.g. vipga)
xmap ga <Plug>(EasyAlign)

" Start interactive EasyAlign for a motion/text object (e.g. gaip)
nmap ga <Plug>(EasyAlign)

set cursorline
" Global indentation settings
filetype plugin indent on

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4

set textwidth=80

" Split shortcuts
nnoremap <C-a> :sp<CR>
set splitbelow
set splitright

" Split navigation with ctrl
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Select the colorscheme
colorscheme solarized
" We use a 256 color terminal

let base16colorspace=256
set background=dark
