#!/usr/bin/python3
# -*- coding: utf-8 -*-
import dbus
import sys
def split_till(candidates, max_length):
    result = ''
    for candidate in candidates:
        result += candidate
        result += ' '
        if len(result) >= max_length:
            return result
session_bus = dbus.SessionBus()
try:
    spotify_bus = session_bus.get_object("org.mpris.MediaPlayer2.spotify",
                                         "/org/mpris/MediaPlayer2")
except:
    sys.exit()
spotify_properties = dbus.Interface(spotify_bus,
                                    "org.freedesktop.DBus.Properties")
metadata = spotify_properties.Get("org.mpris.MediaPlayer2.Player", "Metadata")

# To just print the title
# print metadata['xesam:title']
name_candidates = metadata['xesam:title'].split()
album_candidates = metadata['xesam:album'].split()
MAX_NAME_LENGTH = 20
MAX_ALBUM_LENGTH = 10
name = split_till(name_candidates, MAX_NAME_LENGTH)
album = split_till(album_candidates, MAX_ALBUM_LENGTH)
print_str = '♫ ♪ ' 
if name is not None:
    print_str += name
    if album is not None:
        print_str += '| ' + album
elif album is not None:
    print_str += album


print_str.encode('utf-8')
print(print_str)
