# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell_mod"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

alias tmux="TERM=xterm-256color tmux -2 -u"
alias ":q"="exit"
alias ":e"="vim"

# Colorscheme config
BASE16_SHELL="$HOME/custom/colorschemes/base16-default-dark.sh"
SOLARIZED="$HOME/custom/colorschemes/solarized.sh"
CURRENT_SCHEME="$SOLARIZED"

# Settings for dicolors
eval `dircolors ~/.dircolors`

[[ -s $CURRENT_SCHEME ]] && source $CURRENT_SCHEME

export TERM="xterm-256color"

export PATH="$HOME/custom/bin:$PATH"

eval "$(pyenv init -)"
export PATH="$HOME/.nodenv/bin:$PATH"

export PATH="$HOME/go/bin:$PATH"

export PATH="/usr/local/go/bin:$PATH"
export GOPATH="$HOME/Documents/workspace/go"
export PATH="$GOPATH/bin:$PATH"
export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig

export CPATH="$HOME/custom/include"

#
# Load nodenv automatically by appending
# the following to ~/.zshrc:
#
eval "$(nodenv init -)"

export DEVSTAT_HOME_DIR="$HOME/Workspace"

source "$HOME/custom/scripts/devstat.bash"
