# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell_mod"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git zsh-syntax-highlighting zsh-autosuggestions)

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#0058b3,bg=darkblue,bold,underline'

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

alias tmux="TERM=xterm-256color tmux -2 -u"
alias ":q"="exit"
alias ":e"="vim"

# Colorscheme config
BASE16_SHELL="$HOME/custom/colorschemes/base16-default-dark.sh"
SOLARIZED="$HOME/custom/colorschemes/solarized.sh"
CURRENT_SCHEME="$SOLARIZED"

# Settings for dicolors
eval `dircolors ~/.dircolors`

# [[ -s $CURRENT_SCHEME ]] && source $CURRENT_SCHEME

export TERM="xterm-256color"

export PATH="$HOME/custom/bin:$PATH"

export PATH="$HOME/opt/node-v14.16.1-linux-x64/bin:$PATH"

export PATH="$HOME/opt/saml2aws:$PATH"

export GEM_HOME="$HOME/.gem"

export PATH="$GEM_HOME/bin:$PATH"

export PATH="$HOME/.local/bin:$PATH"


export PATH="$PATH:/usr/local/go/bin"

eval "$(direnv hook zsh)"

alias mygit="$HOME/dev/codecrafters-git-go/your_git.sh"
export CPATH="$HOME/custom/include"

## pyenv configs
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(pyenv init --path)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/shikhar/downloads/google-cloud-sdk/path.zsh.inc' ]; then . '/home/shikhar/downloads/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/shikhar/downloads/google-cloud-sdk/completion.zsh.inc' ]; then . '/home/shikhar/downloads/google-cloud-sdk/completion.zsh.inc'; fi
