name: Docker Image CI

on:
  push:
    branches: [ "Rock/WSL" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: cd workspaces/desk && make build-docker
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }} 
    - name: Push to Docker Hub
      run: cd workspaces/desk && make push-docker
